# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('shortTitle', models.CharField(max_length=20)),
                ('created', models.DateTimeField(editable=False)),
                ('published', models.DateTimeField()),
            ],
        ),
    ]
