# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='Lorem Ipsum dolor sit amet'),
            preserve_default=False,
        ),
    ]
