# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_auto_20170227_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
